[package]
name = "wiesn"
version = "0.1.0"
authors = ["Stuart Heap"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.65"
serde_json = "1.0"
serde = "1.0"
serde_derive = "1.0"

[dependencies.web-sys]
version = "0.3.4"
features = [
  'console',
]
